
version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.16.1
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    links:
      - nodeserver
    expose:
      - "80"
  nodeserver:
    container_name: nodeserver
    build: "./nodeserver"
    volumes:
      - ./nodeserver/ecosystem.config.js:/home/nodeServer/ecosystem.config.js
      - ./nodeserver/server:/home/nodeServer/server
    tty: true
    links:
      - db
      - redis
    ports:
      - "3000:3000"
    expose:
      - "3000"
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/conf/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dbSave.sh:/etc/dbSave.sh
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"
    expose:
      - "3306"
  redis:
    container_name: redis
    image: redis:5.0
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    ports:
      - "6379:6379"
  # 搭建gitlab，通常是用于测试服务器，为了安全请搭建在内网
  gitlab:
    container_name: gitlab
    image: 'twang2218/gitlab-ce-zh:11.1.4'
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
    ports:
      - '8866:80'
      - '466:443'
      - '26:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - '/gitlab/logs:/var/log/gitlab'
      - '/gitlab/data:/var/opt/gitlab'

